name: shoesly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  connectivity: ^3.0.6
  firebase_analytics: ^10.10.6
  firebase_core: ^2.31.1
  firebase_database: ^10.5.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  flutter_xlider: ^3.5.0
  font_awesome_flutter: ^10.7.0
  go_router: ^14.1.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  lottie: ^3.1.2
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.10
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/loading.json
    - assets/emptyCart.json
    - assets/checkedOut.json
    - assets/noResult.json
    - assets/confirmation.json
